### ISSUE TITLE
PopulateListWithCurrentLocationRecycler.java line 94

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/SingBuses#152]
#### in com.itachi1706.busarrivalsg.AsyncTasks.PopulateListWithCurrentLocationRecycler.doInBackground

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.busarrivalsg/issues/5c0a5afff8b88c2963e5986d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.busarrivalsg/issues/5c0a5afff8b88c2963e5986d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.itachi1706.busarrivalsg.gsonObjects.Distance$DistanceItem[] com.itachi1706.busarrivalsg.gsonObjects.Distance.getResults()' on a null object reference
       at com.itachi1706.busarrivalsg.AsyncTasks.PopulateListWithCurrentLocationRecycler.doInBackground(PopulateListWithCurrentLocationRecycler.java:94)
       at com.itachi1706.busarrivalsg.AsyncTasks.PopulateListWithCurrentLocationRecycler.doInBackground(PopulateListWithCurrentLocationRecycler.java:40)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by itachi1706** [comment]
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:353)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
