### ISSUE TITLE
SupportedCardsActivity.java line 84

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/SingBuses#157]
#### in com.itachi1706.cepaslib.activity.SupportedCardsActivity$CardsAdapter.getView

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.busarrivalsg/issues/5c7aa526f8b88c2963ab22d9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.busarrivalsg/issues/5c7aa526f8b88c2963ab22d9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
Seems to be a vector drawable issue? Low Priority i guess as its a 4.3 device. Who uses JB anymore... (0.4% apparently)

**Comment by itachi1706** [comment]
Fatal Exception: android.view.InflateException: Binary XML file line #65: Error inflating class ImageView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at com.itachi1706.cepaslib.activity.SupportedCardsActivity$CardsAdapter.getView(SupportedCardsActivity.java:84)
       at android.widget.AbsListView.obtainView(AbsListView.java:2627)
       at android.widget.ListView.makeAndAddView(ListView.java:1852)
       at android.widget.ListView.fillDown(ListView.java:682)
       at android.widget.ListView.fillFromTop(ListView.java:748)
       at android.widget.ListView.layoutChildren(ListView.java:1667)
       at android.widget.AbsListView.onLayout(AbsListView.java:2447)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1666)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1442)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2260)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:76)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:51)
       at androidx.test.espresso.action.Tap.c(Tap.java:8)
       at androidx.test.espresso.action.Tap.a(Tap.java:18)
       at androidx.test.espresso.action.Tap$1.b(Tap.java:3)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by android.content.res.Resources$NotFoundException: File res/drawable/locked.xml from drawable resource ID #0x7f0800b1
       at android.content.res.Resources.loadDrawable(Resources.java:2974)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.ImageView.(ImageView.java:131)
       at androidx.appcompat.widget.AppCompatImageView.(AppCompatImageView.java:72)
       at androidx.appcompat.widget.AppCompatImageView.(AppCompatImageView.java:68)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at com.itachi1706.cepaslib.activity.SupportedCardsActivity$CardsAdapter.getView(SupportedCardsActivity.java:84)
       at android.widget.AbsListView.obtainView(AbsListView.java:2627)
       at android.widget.ListView.makeAndAddView(ListView.java:1852)
       at android.widget.ListView.fillDown(ListView.java:682)
       at android.widget.ListView.fillFromTop(ListView.java:748)
       at android.widget.ListView.layoutChildren(ListView.java:1667)
       at android.widget.AbsListView.onLayout(AbsListView.java:2447)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1666)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1442)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:15204)
       at android.view.ViewGroup.layout(ViewGroup.java:4793)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2260)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:76)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:51)
       at androidx.test.espresso.action.Tap.c(Tap.java:8)
       at androidx.test.espresso.action.Tap.a(Tap.java:18)
       at androidx.test.espresso.action.Tap$1.b(Tap.java:3)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by itachi1706** [comment]
Fixed 6829f9cf9a41cad0fb13c076489bbf4787f439e5
